time="2026-04-08T12:04:18Z" level=warning msg="/home/ubuntu/claude-agent-system/pixreveal/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
"""initial_tables

Revision ID: 619fc04f4dac
Revises: 
Create Date: 2026-04-08 12:04:09.900806
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '619fc04f4dac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
