class L {
  static const Map<String, String> _tr = {
    'main_menu_subtitle': 'Gizli görseli açığa çıkar.',
    'play': 'Oyna',
    'shop': 'Mağaza',
    'settings': 'Ayarlar',
    'shop_title': 'Mağaza',
    'free_tokens': 'Ücretsiz Jetonlar',
    'watch_ad_for_free_tokens': 'Jeton kazanmak için reklam izle',
    'watch_ad': 'Reklam İzle',
    'token_packs': 'Jeton Paketleri',
    'premium_themes': 'Premium Temalar',
    'subscription': 'Abonelik',
    'unlock_everything': 'Her şeyin kilidini aç',
    'go_premium': 'Premium Ol',
    'sound': 'Ses',
    'sound_effects': 'Ses Efektleri',
    'music': 'Müzik',
    'vibration': 'Titreşim',
    'account': 'Hesap',
    'guest_account': 'Misafir Hesabı',
    'link_account': 'Hesabı Bağla',
    'purchases': 'Satın Alımlar',
    'restore_purchases': 'Satın Alımları Geri Yükle',
    'legal': 'Yasal',
    'privacy_policy': 'Gizlilik Politikası',
    'terms_of_service': 'Kullanım Şartları',
    'language': 'Dil',
    'select_category': 'Kategori Seç',
    'level_1': 'Seviye 1',
    'your_own_image': 'Kendi Görselin',
    'victory': 'Zafer',
    'next_level': 'Sonraki Seviye',
    'retry': 'Tekrar Dene',
    'menu': 'Menü',
    'game_over': 'Oyun Bitti',
    'continue_question': 'Devam etmek ister misin?',
    'use_1_token': '1 Jeton Kullan',
    'unlimited_tokens': 'Sınırsız Jeton',
    'all_theme_packs': 'Tüm Tema Paketleri',
    'custom_images': 'Özel Görseller',
    'no_ads': 'Reklamsız',
    'exclusive_powerups': 'Özel Güçler',
    'subscribe': 'Abone Ol',
    'paywall_legal_small': 'Abonelik dönem sonunda otomatik yenilenir.',
  };

  static String get(String key) => _tr[key] ?? key;
}
