// Generated by manual Firebase setup for pixreveal-prod
// Project: pixreveal-prod (432979162987)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static bool get isWeb => identical(0, 0.0);

  static FirebaseOptions get currentPlatformOrWeb {
    if (isWeb) return web;
    return currentPlatform;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnkZnwHr-7CMsoQ-1x5Bg1kyYKBtNBloY',
    appId: '1:432979162987:web:pixreveal9c7e2e',
    messagingSenderId: '432979162987',
    projectId: 'pixreveal-prod',
    authDomain: 'pixreveal-prod.firebaseapp.com',
    storageBucket: 'pixreveal-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnkZnwHr-7CMsoQ-1x5Bg1kyYKBtNBloY',
    appId: '1:432979162987:android:6fa2c3324341fcdf9c7e2e',
    messagingSenderId: '432979162987',
    projectId: 'pixreveal-prod',
    storageBucket: 'pixreveal-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjA4Y8IyIvHIUluHstqd0mv0kQQliqKw',
    appId: '1:432979162987:ios:dd50509c011e8b059c7e2e',
    messagingSenderId: '432979162987',
    projectId: 'pixreveal-prod',
    storageBucket: 'pixreveal-prod.firebasestorage.app',
    iosBundleId: 'com.cytbilisim.pixreveal',
  );
}
